// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCHTdGbtBBq2zBqecOIgbmD1xIoow48ngQ',
    appId: '1:927193034901:web:34b8279fff70c4c26feb9c',
    messagingSenderId: '927193034901',
    projectId: 'communicatordb-bf810',
    authDomain: 'communicatordb-bf810.firebaseapp.com',
    storageBucket: 'communicatordb-bf810.firebasestorage.app',
    measurementId: 'G-H40YK7HH9H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYlGP_GTUjpuuZXO6NyLyH4pTRB9aw_Gk',
    appId: '1:927193034901:android:8ecb3f5847cc3e046feb9c',
    messagingSenderId: '927193034901',
    projectId: 'communicatordb-bf810',
    storageBucket: 'communicatordb-bf810.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2KrT_AxoUlf1fRf6zQszGFiYnM6a32jM',
    appId: '1:927193034901:ios:bd0e75d5f0722c306feb9c',
    messagingSenderId: '927193034901',
    projectId: 'communicatordb-bf810',
    storageBucket: 'communicatordb-bf810.firebasestorage.app',
    iosBundleId: 'com.example.communicator',
  );
}
